# Generated by Django 5.2.7 on 2025-10-25 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bulan', models.CharField(max_length=20)),
                ('tahun', models.IntegerField()),
                ('status', models.CharField(choices=[('BELUM_LUNAS', 'Belum Lunas'), ('LUNAS', 'Lunas'), ('KADALUARSA', 'Kadaluarsa')], default='BELUM_LUNAS', max_length=20)),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_bayar', models.DateTimeField(auto_now_add=True)),
                ('jumlah_bayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_transaksi_gateway', models.CharField(max_length=100)),
                ('metode_pembayaran', models.CharField(max_length=50)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran.tagihan')),
            ],
        ),
    ]
