# Generated by Django 5.2.7 on 2025-10-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihan',
            name='status',
            field=models.CharField(choices=[('BELUM_LUNAS', 'Belum Lunas'), ('PENDING', 'Menunggu Pembayaran'), ('LUNAS', 'Lunas'), ('KADALUARSA', 'Kadaluarsa / Batal')], default='BELUM_LUNAS', max_length=20),
        ),
    ]
