# Generated by Django 5.2.7 on 2025-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0002_alter_tagihan_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pembayaran',
            options={'verbose_name': 'Pembayaran', 'verbose_name_plural': 'Pembayaran'},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'verbose_name': 'Siswa', 'verbose_name_plural': 'Siswa'},
        ),
        migrations.AlterModelOptions(
            name='tagihan',
            options={'verbose_name': 'Tagihan', 'verbose_name_plural': 'Tagihan'},
        ),
        migrations.AddField(
            model_name='tagihan',
            name='jumlah_terbayar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='status',
            field=models.CharField(choices=[('BELUM_LUNAS', 'Belum Lunas'), ('PENDING', 'Menunggu Pembayaran'), ('CICILAN', 'Dicicil / Kurang Bayar'), ('LUNAS', 'Lunas'), ('KADALUARSA', 'Kadaluarsa / Batal')], default='BELUM_LUNAS', max_length=20),
        ),
    ]
