# Generated by Django 5.2.7 on 2025-11-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0004_alter_tagihan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='id_transaksi_gateway',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
