# Generated by Django 5.2.7 on 2025-11-25 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0005_alter_pembayaran_id_transaksi_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran',
            name='id_transaksi_gateway',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='jumlah_bayar',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='metode_pembayaran',
            field=models.CharField(default='MANUAL/CASH', max_length=50),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='tagihan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembayaran.tagihan'),
        ),
    ]
