# Generated by Django 5.2.7 on 2025-11-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0006_alter_pembayaran_id_transaksi_gateway_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuatTagihanMassal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kelas', models.CharField(choices=[('7A', '7A'), ('7B', '7B'), ('8A', '8A'), ('8B', '8B'), ('9A', '9A'), ('9B', '9B'), ('SEMUA', 'Semua Kelas')], max_length=10)),
                ('judul_tagihan', models.CharField(help_text='Contoh: SPP Bulan Agustus 2025', max_length=200)),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=10)),
                ('bulan', models.CharField(max_length=20)),
                ('tahun', models.IntegerField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buat Tagihan Massal',
                'verbose_name_plural': 'Buat Tagihan Massal',
            },
        ),
        migrations.AlterField(
            model_name='tagihan',
            name='jumlah',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
